- menu_name: "Fale Conosco"

- name: "Mande uma mensagem"
  url: "/contato/"
  title: "Contato"

- name: "Facebook"
  url: "http://facebook.com.br/pr0gamers"
  title: "Visite nossa página no Facebook"

#- name: "RSS"
#  url: "/feed.xml"
#  title: "Subscribe to RSS Feed"

#- name: "Atom"
#  url: "/atom.xml"
#  title: "Subscribe to Atom Feed"

#- name: "sitemap.xml"
#  url: "/sitemap.xml"
#  title: "Sitemap for Google Webmaster Tools"
